# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sponsorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsorships_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="sponsored",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsorships_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foundercohort",
            name="members",
            field=models.ManyToManyField(
                related_name="founder_cohorts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sponsorship",
            unique_together={("sponsor", "sponsored")},
        ),
    ]
