# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rigor_score", models.FloatField()),
                ("engagement_score", models.FloatField()),
                ("recency_score", models.FloatField()),
                ("total_score", models.FloatField()),
                ("cached_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-total_score", "-cached_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFeedPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_rigor_threshold",
                    models.FloatField(
                        default=0.0, help_text="Minimum rigor score (0-2)"
                    ),
                ),
            ],
        ),
    ]
