# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feed", "0001_initial"),
        ("theses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedpreference",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userfeedpreference",
            name="preferred_tags",
            field=models.ManyToManyField(blank=True, to="tags.tag"),
        ),
        migrations.AddField(
            model_name="userfeedpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="theses.minithesis"
            ),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feeditem",
            unique_together={("user", "thesis")},
        ),
    ]
