# Generated by Django 4.2.7 on 2026-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tag_accuracy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsorship_status',
            field=models.CharField(choices=[('pending', 'Pending sponsor validation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
