# Generated by Django 4.2.7 on 2026-04-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_contacts_contactrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cookies_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
