# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("factual_reference_needed", "[référence nécessaire]"),
                            ("factual_primary_needed", "[source primaire requise]"),
                            ("factual_contested", "[source contestée]"),
                            ("factual_dead_link", "[lien mort]"),
                            ("factual_misinterpreted", "[source mal interprétée]"),
                            ("logical_non_sequitur", "[non sequitur]"),
                            ("logical_overgeneralization", "[généralisation abusive]"),
                            ("logical_correlation", "[corrélation/causalité]"),
                            ("logical_undeclared", "[travail inédit non déclaré]"),
                            ("normative_implicit", "[prémisse implicite]"),
                            ("normative_contradictory", "[prémisse contradictoire]"),
                            ("normative_exceeds", "[conclusion excède les prémisses]"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Explanation of what this tag means"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justification", models.TextField(help_text="Why this tag applies")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("resolved_positive", "Resolved - Valid"),
                            ("resolved_negative", "Resolved - Invalid"),
                            ("disputed", "Currently Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("downvotes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TagVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_upvote", models.BooleanField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tag_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="tags.tagapplication",
                    ),
                ),
            ],
        ),
    ]
