# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagvote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tagapplication",
            name="applied_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tagapplication",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tagapplication",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tags.tag"
            ),
        ),
        migrations.AddField(
            model_name="tagapplication",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="theses.minithesis",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tagvote",
            unique_together={("tag_application", "voter")},
        ),
        migrations.AlterUniqueTogether(
            name="tagapplication",
            unique_together={("tag", "thesis", "applied_by")},
        ),
    ]
