[pytest]
pythonpath = src
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Test
python_functions = test_*
testpaths =
	src/apps/users
	src/apps/theses
	tests
norecursedirs = apps/migrations