# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="minithesis",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="theses.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="theses.minithesis",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="cited_thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations_received",
                to="theses.minithesis",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="citing_thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations_made",
                to="theses.minithesis",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="citation",
            unique_together={("citing_thesis", "cited_thesis")},
        ),
    ]
