# Generated by Django 4.2.7 on 2026-04-11 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0002_initial"),
        ("theses", "0003_minithesis_parent_thesis"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThesisReviewHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("thesis", "Thesis"),
                            ("facts", "Facts"),
                            ("normative_premises", "Normative premises"),
                            ("conclusion", "Conclusion"),
                            ("declared_limits", "Declared limits"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "selected_text",
                    models.TextField(help_text="Exact text selected by the reviewer."),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thesis_review_highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tags.tag"
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_highlights",
                        to="theses.minithesis",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
