# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("moderation", "0001_initial"),
        ("theses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theses.comment",
            ),
        ),
    ]
