# Generated by Django 4.2.7 on 2026-04-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theses", "0001_initial"),
        ("moderation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationaction",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="thesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theses.minithesis",
            ),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="editorialreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="editorialreview",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="theses.minithesis",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="editorialreview",
            unique_together={("thesis", "reviewer")},
        ),
    ]
